---
title: "DATIC: Introduction to R Workshop"
author: "Instructor: Randi L. Garcia"
date: "June 7th and 8th, 2018"
output:
  html_document:
    highlight: pygments
    theme: cerulean
    toc: yes
    toc_depth: 3
    toc_float: yes
  pdf_document:
    toc: yes
    toc_depth: '3'
fontsize: 12 pt
---

 > **Workshop location**: Gentry 140, 9:00am - 5:00pm.  
 > **Textbook**: [R for Data Science](http://r4ds.had.co.nz/index.html)  
 > **Teaching Assistant**: Starry Zhou

***

#Schedule

##[Day 1: Introduction to R](Day 1 Slides.pdf)

  + Morning Session 9-12
    - [Intro to the RStudio environment, and RMarkdown](Intro_to_R.html)
    - [Intro to packages and descriptive statistics](packages_descriptives.html)
    - [Making Figures with `ggplot2`](Intro_to_ggplot2.html)  
  + Lunch 12:00 PM to 1:15 PM
  + Afternoon Session 1:15-3:30
    - [Data Manipulation and descriptive statistics with `dplyr`](Intro_to_dplyr.html)  
    - [Correlations, Reliability Test, and Scale Scores](cor_reliability_ttest.html)
  + Homework
    - Download and install [miktex](https://miktex.org/)  
  + [Basic Intro Stats Labs](http://www.science.smith.edu/~rgarcia/sds201-S18/index.html)
    - [`dplyr` lab](http://www.science.smith.edu/~rgarcia/sds201-S18/labs/intro_to_data.html)
    - [`ggplot` lab](http://www.science.smith.edu/~rgarcia/sds201-S18/labs/data_visualization.html)
    - [T-tests](http://www.science.smith.edu/~rgarcia/sds201-S18/labs/inf_for_numerical_data.html)


***

##[Day 2: Data Analysis in R](Day 2 Slides.pdf)

  + Morning Session 9-12
    - [Data Restructuring with `tidyr`](Restructuring_with_tidyr.html)
    - [ANOVA, Regression, and Logistic regression](ANOVA_and_regression.html)
    - Preparing [APA style manuscripts](ReproducibleAPAstyle.pdf) in R Markdown with `papaja`
    - [Downloading data from Qualtrics into R](Downloading_qualtrics_data.html)
  + Lunch 12:00 PM to 1:15 PM  
  + Afternoon Session 1:15-3:30
    - [Exploratory Factor Analysis (EFA)](Exploratory_Factor_Analysis.html)
    - [Confirmatory Factor Analysis (CFA) and SEM with `laavan`](Confirmatory_Factor_Analysis_and_SEM.html)
  + [Experimental Design Labs](http://www.science.smith.edu/~rgarcia/sds290-S18/index.html) and other resources  
    - [Multiple Regression](http://www.science.smith.edu/~rgarcia/sds201-S18/labs/multiple_regression.html)
    - [Two-way ANOVA](http://www.science.smith.edu/~rgarcia/sds290-S18/lectures/09_bf2_inR.Rmd)
    - [Repeated Measures, Latin Square, and Mixed ANOVA](http://www.science.smith.edu/~rgarcia/sds290-S18/lectures/13_spitplot_design_inR.Rmd)
    - [Factor Analysis with `psych`](factor.pdf)
    - [`lavaan` tutorials](http://lavaan.ugent.be/tutorial/)

***

#Cheatsheets, R Tutorials, and Books

  + [dplyr cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/data-transformation.pdf)
  + [ggplot2 cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/data-visualization-2.1.pdf)
  + [RMarkdown cheatsheet](https://github.com/rstudio/cheatsheets/raw/master/rmarkdown-2.0.pdf) 
      - [Advanced RMarkdown](http://rmarkdown.rstudio.com/authoring_pandoc_markdown.html)



